### ISSUE TITLE
Shapefile for Comprehensive Example not working correctly on Shiny site

### ISSUE THREAD

**Issue by WayneBetws** [andrejadd/GWSDAT#215]
![screenshot](https://user-images.githubusercontent.com/38751080/44535056-17b70680-a6f1-11e8-9188-5355031f2d35.JPG)

**Comment by andrejadd** [comment]
Plotting the shape lines triggers this bug. I replaced 

plot(shape_data[[i]], add = TRUE, col = "lightblue", max.plot = 1)

with 

plot(st_geometry(shape_data[[i]]), add = TRUE, max.plot = 1, col = "lightblue")

st_geometry transforms the shape data. 

Confirm with other shape data besides the comprehensive data...

**Comment by andrejadd** [comment]
last frame seems a little off but looking at previous frames it looks as if it fits (here January 2009):

![spatialplot2](https://user-images.githubusercontent.com/12441470/47437013-10a68600-d77e-11e8-8e3a-866cb5bc8873.png)
